#!/usr/bin/env bash

set -e

npm run build

rm -rf out/EaglerForge*

git add .

git commit -m "setupbuild commit" || echo "Nothing to commit"

git pull --rebase origin main

git push origin HEAD:main
